### PR TITLE
Add support for PostInstall in integration configs, fix tests

### LINKED ISSUE #39: Add support for post_install blocks
The web interface already has the ability to display additional blocks that are displayed after the integration has been successfully applied. I think these can be very handy when you want to convey some additional steps the user can/should do; as an example when you install a package with `apt` or `brew` they'll very often provide an additional document suggesting next steps, (eg. initializing the database or enabling a service).

Example:

```yaml
---
api_version: catalog/v1
type: Integration
metadata:
  namespace: kubernetes
  name: kubernetes-monitoring
spec:
  class: supported
  provider: monitoring
  display_name: Kubernetes monitoring
  short_description: Kubernetes API liveness health check.
  supported_platforms:
    - darwin
    # ...
  tags:
    - kubernetes
    # ...
  contributors:
    - "@sensu"
  prompts:
    # ...
  resource_patches:
    # ...
  post_install:
    - type: section
      title: Next Steps
    - type: markdown
      body: |
1. Add the "nginx" subscription to agents that should run this check.

   **NOTE:** set the optional `check_nginx_status_url` agent annotation to override the default URL (`http://localhost:80/nginx_status`).

1. Ensure the [NGINX `stub_status` module][nginx_stub_status] is enabled on the NGINX instances(s) to be monitored.

   **NOTE:** the following example NGINX configuration snippet shows how to enable the `stub_status` module:

   \```
   # NGINX Status Module
   location /nginx_status {
       stub_status;
       allow 0.0.0.0;
   }
   \```
```

### PR DESCRIPTION
**Pull request by amdprophet**
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>

Closes #39. 

@jamesdphillips I based this off the information in #39; let me know if this will work for you.

### CODE REVIEW

File: internal/api/catalog/v1/integration.go [hunk 1]
```diff
@@ -28,6 +28,34 @@ type ResourcePatchRef struct {
...
+		if p.Body == "" {
+			return errors.New("body cannot be empty for type markdown")
+		}
+		if p.Title != "" {
+			return errors.New("title must be empty for type markdown")
+		}
+	case "section":
+		if p.Title == "" {
+			return errors.New("title cannot be empty for type section")
+		}
```
Comment (jamesdphillips) [inline internal/api/catalog/v1/integration.go:49]:
```suggestion
```

the frontend allows both the title and body fields to be empty for sections

**Review by jamesdphillips — APPROVED** [review]
Thanks for fixing up the tests
